export { Login, Register } from './Unprotected';
export { 
    Users, 
    Home, 
    Prizes, 
    Profile, 
    Services, 
    Subscription, 
    History, 
    Payment, 
    Wallet,
    CreatePrize,
    EditPrize,
    CreateCreditCard,
    EditAddress,
    Employee,
    EditStablishment,
    Notifications,
    Points,
} from './Protected';
