export { Login, Register, Recover } from './Unprotected';
export { 
    Users, 
    Home, 
    Prizes, 
    Profile, 
    Services, 
    Subscription, 
    History, 
    Payment, 
    Wallet,
    CreatePrize,
    EditPrize,
    CreateCreditCard,
    EditAddress,
    Employee,
    EditStablishment,
    Notifications,
    Points,
    Sales,
    CreateSale,
    SendSale,
    EditSale,
    Redeem
} from './Protected';
